### ISSUE TITLE
"response is already locked" error state after using "git copy file" on locally modified file

### ISSUE THREAD

**Issue by saidelike** [AndreasArvidsson/andreas-talon#11]
If you say `git copy file` when on a file that has been modified locally, you get this warning which is expected:

![image](https://github.com/AndreasArvidsson/andreas-talon/assets/387346/d64c7601-ef79-48d6-9010-98636c28e9a8)

However, from now on, you can't use that command anymore until you restart vscode and you'll get this error (even on an unmodified local file):

![image](https://github.com/AndreasArvidsson/andreas-talon/assets/387346/5af086d9-8b35-4d20-b2a4-8d6404d356f1)

**Comment by AndreasArvidsson** [comment]
It's actually waiting for you to close the error message. I have now released a new version without this behavior.
