### ISSUE TITLE
`clippy_hint` capture uses nonstandard lists

### ISSUE THREAD

**Issue by pokey** [AndreasArvidsson/andreas-talon#12]
https://github.com/AndreasArvidsson/andreas-talon/blob/24455da4e8bd5ed4ed13538530d0f2bc848451a6/plugins/clippy/clippy_targets.py#L31

**Comment by pokey** [comment]
Right now I'm running clippy-talon using a shallow clone of this repo:

```sh
git clone -n --depth=1 --filter=tree:0 'git@github.com:AndreasArvidsson/andreas-talon.git' clippy-talon
cd clippy-talon 
git sparse-checkout set plugins/clippy core/rpc_client
git checkout
```

**Comment by AndreasArvidsson** [comment]
This is going a have to change if I'm moving this into a separate repository. At long as its in my repository it's of course going to be based upon my lists and captures. You can just make a context specific override on that capture?

**Comment by pokey** [comment]
Yeah that's what I ended up doing. Pasting here for reference:


```py
from talon import Context

ctx = Context()


@ctx.capture(rule="<user.number_key> | {user.letter} [{user.letter}]")
def clippy_hint(m) -> str:
    try:
        return str(m.number_key)
    except AttributeError:
        return "".join(m.letter_list)
```

**Comment by AndreasArvidsson** [comment]
Nice. Thank you :)
I guess neither of those lists are mac specific though? Since it's already on a context it should win over the default module definition so you don't need to think about specificity.

**Comment by pokey** [comment]
oh really? I thought I had to have something on the context for it to win

**Comment by AndreasArvidsson** [comment]
Nope. Global context wins over global module.

**Comment by pokey** [comment]
Ok I edited the code snippet. Haven't tested it, but will take your word for it

**Comment by AndreasArvidsson** [comment]
Fixed now
