### ISSUE TITLE
Add spoken command to pin clippy

### ISSUE THREAD

**Issue by pokey** [AndreasArvidsson/andreas-talon#13]
Eg saying `"clippy pin"` should show clippy if it's not already showing, and cause it to stay put after a paste. Equivalent to clicking the pin in the top right

**Comment by AndreasArvidsson** [comment]
Showing the window if it's hidden when you issue this command is no problem. `"clippy pin"` is defined as `togglePinned`. That means that if it was pinned and you issue that command it will be unpinned now. 
Basically show window if hidden and then toggle pinned. Does that work for you?

**Comment by pokey** [comment]
I think that's ok. Is it possible for it to be pinned and hidden? If so, then I would be surprised when "clippy pin" results in it appearing and not being pinned

I would be tempted to have "clippy pin" and "clippy unpin". Idempotence is nice

**Comment by AndreasArvidsson** [comment]
It can definitely be pinned and hidden. If it's pin you can still hide it. Do you think that should unpin it?

I can add both set and toggle.

**Comment by AndreasArvidsson** [comment]
I have now added idempotent command identifiers to all toggle commands.
https://github.com/AndreasArvidsson/andreas-talon/blob/03ec15e089a80c56a2fab33a1d7f3f13bf72d86e/plugins/clippy/clippy.py#L22-L44
