### ISSUE TITLE
Insert snippets error

### ISSUE THREAD

**Issue by x0aa7i** [AndreasArvidsson/andreas-talon#3]
`actions.user.insert_snippet()` raise an error in vscode.
```
TypeError: vscode() takes 1 positional argument but 2 were given
```

**Comment by AndreasArvidsson** [comment]
My implementation of `user.vscode` is the same as what's on knausj is `user.vscode_with_plugin`. 

https://github.com/AndreasArvidsson/talon-vscode-command-client/blob/f133eebad8e0e4f383d63be94a7d1d07aa06f586/command_client.py#L297-L313

**Comment by x0aa7i** [comment]
My bad, I'm using Pokey's repo, I thought they were the same 😅

**Comment by AndreasArvidsson** [comment]
Most of the code I use is tweaked in some way. You know... why not? :D

**Comment by x0aa7i** [comment]
I love the code man, great stuff⚡

**Comment by AndreasArvidsson** [comment]
Glad to hear it :)
