### ISSUE TITLE
memory leak for imgui

### ISSUE THREAD

**Issue by SmikeSix** [AndreasArvidsson/andreas-talon#5]
hey i extended this class to add some horizontal panels / toogle buttons and seralization and found that it is quite gpu / cpu heavy since it will be redrawn every frame. and this causes heavy memory leaks.
you need to pause / resume the ui on content changes.

on the other side, do you know if there is a way to have text input fields with it?

**Comment by AndreasArvidsson** [comment]
There is a `imgui.freeze()` function available that you could use. That it by default always updates is desirable for my use cases and the cpu and memory drain is manageable for me.

I haven't experimented with text input fields.

**Comment by SmikeSix** [comment]
just to mention, its a windows only bug that is in some framework talon uses, it will be patched out in newer versions
