### ISSUE TITLE
some clippy text entries are way too big, making clippy window very wide

### ISSUE THREAD

**Issue by jmegner** [AndreasArvidsson/andreas-talon#8]
When I copy plain text or rich text from Microsoft Outlook, clippy entries have a very reasonable plain text view of the text.  When I copy from Microsoft OneNote, clippy shows the entry like a very zoomed in (pixelated) and wide picture of the text.  This very wide entry makes the clippy window also grow very wide (sometimes wider than my 1920x1080 monitor).  Not sure what else could cause this behavior, but I've noticed it with OneNote.

![image](https://github.com/AndreasArvidsson/andreas-talon/assets/539362/8331a44f-1afb-40e4-ae20-4ff1219ed265)

**Comment by AndreasArvidsson** [comment]
That looks like an image. For some reason it was copied as an image. I probably just need to limit the maximum width on images.

**Comment by AndreasArvidsson** [comment]
I have now updated the code to clamp image width

https://github.com/AndreasArvidsson/andreas-talon/commit/f04e73efb56e17939d161348b65c23cd46c44613
